name: Build, Test and Deploy Addgram backend

on:
  push:
    branches: [dev]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Injecting environment vars
        run: |
          echo "${{ secrets.TEST_SECRETS }}" >> .env
      - name: Building Docker containers
        run: |
          docker-compose up -d --build
      - name: Running Tests inside Docker containers
        run: |
          docker-compose exec -T api pytest

  deploy:
    name: Deploying on EC2 via SSH
    if: ${{ github.event_name == 'push' }}
    needs: [build-test]
    runs-on: ubuntu-latest
    steps:
      - name: Deploying Application on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_EC2_IP }}
          username: ${{ secrets.SSH_EC2_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            cd ~/.scripts
            ./docker-ec2-deploy.sh
